name: LINE notify

on:
  schedule:
    - cron: '0 22 * * *'
  workflow_dispatch:

jobs:
  send-line-message:
    runs-on: ubuntu-latest
    env:
      PYTHONIOENCODING: utf-8
      LANG: ja_JP.UTF-8

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: install
        run: pip install requests feedparser beautifulsoup4

      - name: send
      env:
        LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
        LINE_USER_ID: ${{ secrets.LINE_USER_ID }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: python running_line_bot.py
